In [1]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [5]:
import glob

In [3]:
from fastai.structured import *
from fastai.column_data import *
import pandas as pd
np.set_printoptions(threshold=50, edgeitems=20)

PATH = 'fixed/data/'

/home/bahram/anaconda3/envs/fastai/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/bahram/anaconda3/envs/fastai/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/bahram/anaconda3/envs/fastai/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [4]:
from biopandas.pdb import PandasPdb

In [6]:
all_files = glob.glob(os.path.join(PATH, "*"))

In [7]:
all_files[:10]

['fixed/data/4g4sP00.pdb',
 'fixed/data/4a27A02.pdb',
 'fixed/data/3lwsA01.pdb',
 'fixed/data/2xzmW03.pdb',
 'fixed/data/3ztaA00.pdb',
 'fixed/data/2bhsB01.pdb',
 'fixed/data/1d1rA00.pdb',
 'fixed/data/5cbeE00.pdb',
 'fixed/data/3tqmA00.pdb',
 'fixed/data/4uy9A01.pdb']

In [69]:
fname= all_files[0]
fname2= all_files[1]
pl1 = PandasPdb().read_pdb(f'{fname}')
pl2 = PandasPdb().read_pdb(f'{fname2}')
df= pd.DataFrame()
d=pd.DataFrame()
i=0
for fnam in all_files[1:50]:
    pl = PandasPdb().read_pdb(f'{fnam}')
    pl1.df['ATOM']=pl1.df['ATOM'].append(pl.df['ATOM'])
    #pl = d
    i=i+1
    print(i)
pl1.df['ATOM']

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
0,ATOM,1,,N,,MET,,A,1,,...,38.763,40.932,11.492,1.0,0.0,,,N,NaN,1
1,ATOM,2,,CA,,MET,,A,1,,...,37.390,40.466,11.665,1.0,0.0,,,C,NaN,2
2,ATOM,3,,C,,MET,,A,1,,...,36.434,41.158,10.694,1.0,0.0,,,C,NaN,3
3,ATOM,4,,O,,MET,,A,1,,...,36.174,40.649,9.601,1.0,0.0,,,O,NaN,4
4,ATOM,5,,CB,,MET,,A,1,,...,36.924,40.679,13.110,1.0,0.0,,,C,NaN,5
5,ATOM,6,,CG,,MET,,A,1,,...,35.532,40.128,13.427,1.0,0.0,,,C,NaN,6
6,ATOM,7,,SD,,MET,,A,1,,...,35.422,38.321,13.451,1.0,0.0,,,S,NaN,7
7,ATOM,8,,CE,,MET,,A,1,,...,33.815,38.072,14.207,1.0,0.0,,,C,NaN,8
8,ATOM,9,,N,,SER,,A,2,,...,35.930,42.325,11.090,1.0,0.0,,,N,NaN,9
9,ATOM,10,,CA,,SER,,A,2,,...,34.813,42.979,10.397,1.0,0.0,,,C,NaN,10
10,ATOM,11,,C,,SER,,A,2,,...,35.082,43.459,8.966,1.0,0.0,,,C,NaN,11
11,ATOM,12,,O,,SER,,A,2,,...,36.105,44.092,8.670,1.0,0.0,,,O,NaN,12
12,ATOM,13,,CB,,SER,,A,2,,...,34.260,44.137,11.235,1.0,0.0,,,C,NaN,13
13,ATOM,14,,OG,,SER,,A,2,,...,33.684,43.655,12.434,1.0,0.0,,,O,NaN,14
14,ATOM,15,,N,,CYS,,A,3,,...,34.129,43.168,8.089,1.0,0.0,,,N,NaN,15
15,ATOM,16,,CA,,CYS,,A,3,,...,34.220,43.589,6.704,1.0,0.0,,,C,NaN,16
16,ATOM,17,,C,,CYS,,A,3,,...,32.863,44.041,6.157,1.0,0.0,,,C,NaN,17
17,ATOM,18,,O,,CYS,,A,3,,...,31.843,43.369,6.350,1.0,0.0,,,O,NaN,18
18,ATOM,19,,CB,,CYS,,A,3,,...,34.807,42.465,5.850,1.0,0.0,,,C,NaN,19
19,ATOM,20,,SG,,CYS,,A,3,,...,34.896,42.842,4.103,1.0,0.0,,,S,NaN,20
20,ATOM,21,,N,,LEU,,A,4,,...,32.857,45.194,5.496,1.0,0.0,,,N,NaN,21
21,ATOM,22,,CA,,LEU,,A,4,,...,31.657,45.701,4.835,1.0,0.0,,,C,NaN,22
22,ATOM,23,,C,,LEU,,A,4,,...,31.743,45.522,3.315,1.0,0.0,,,C,NaN,23
23,ATOM,24,,O,,LEU,,A,4,,...,32.768,45.845,2.691,1.0,0.0,,,O,NaN,24
24,ATOM,25,,CB,,LEU,,A,4,,...,31.431,47.182,5.161,1.0,0.0,,,C,NaN,25
25,ATOM,26,,CG,,LEU,,A,4,,...,30.509,47.901,4.166,1.0,0.0,,,C,NaN,26
26,ATOM,27,,CD1,,LEU,,A,4,,...,29.075,47.473,4.377,1.0,0.0,,,C,NaN,27
27,ATOM,28,,CD2,,LEU,,A,4,,...,30.642,49.415,4.258,1.0,0.0,,,C,NaN,28
28,ATOM,29,,N,,VAL,,A,5,,...,30.669,45.000,2.721,1.0,0.0,,,N,NaN,29
29,ATOM,30,,CA,,VAL,,A,5,,...,30.549,44.996,1.261,1.0,0.0,,,C,NaN,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,ATOM,560,,CG,,HIS,,A,68,,...,19.373,11.580,50.135,1.0,0.0,,,C,NaN,560
560,ATOM,561,,ND1,,HIS,,A,68,,...,20.564,12.229,50.378,1.0,0.0,,,N,NaN,561
561,ATOM,562,,CD2,,HIS,,A,68,,...,18.646,12.415,49.357,1.0,0.0,,,C,NaN,562
562,ATOM,563,,CE1,,HIS,,A,68,,...,20.554,13.406,49.781,1.0,0.0,,,C,NaN,563
563,ATOM,564,,NE2,,HIS,,A,68,,...,19.400,13.545,49.155,1.0,0.0,,,N,NaN,564
564,ATOM,565,,N,,PRO,,A,69,,...,21.156,10.196,53.243,1.0,0.0,,,N,NaN,565
565,ATOM,566,,CA,,PRO,,A,69,,...,22.399,10.704,53.832,1.0,0.0,,,C,NaN,566
566,ATOM,567,,C,,PRO,,A,69,,...,23.195,11.710,52.992,1.0,0.0,,,C,NaN,567
567,ATOM,568,,O,,PRO,,A,69,,...,23.190,11.672,51.757,1.0,0.0,,,O,NaN,568
568,ATOM,569,,CB,,PRO,,A,69,,...,23.182,9.430,54.139,1.0,0.0,,,C,NaN,569
569,ATOM,570,,CG,,PRO,,A,69,,...,22.621,8.432,53.177,1.0,0.0,,,C,NaN,570
570,ATOM,571,,CD,,PRO,,A,69,,...,21.163,8.727,53.197,1.0,0.0,,,C,NaN,571
571,ATOM,572,,N,,ARG,,A,70,,...,23.886,12.607,53.691,1.0,0.0,,,N,NaN,572
572,ATOM,573,,CA,,ARG,,A,70,,...,24.683,13.671,53.082,1.0,0.0,,,C,NaN,573
573,ATOM,574,,C,,ARG,,A,70,,...,25.943,13.270,52.319,1.0,0.0,,,C,NaN,574
574,ATOM,575,,O,,ARG,,A,70,,...,26.801,12.583,52.857,1.0,0.0,,,O,NaN,575
575,ATOM,576,,CB,,ARG,,A,70,,...,25.121,14.653,54.152,1.0,0.0,,,C,NaN,576
576,ATOM,577,,CG,,ARG,,A,70,,...,24.046,15.150,55.039,1.0,0.0,,,C,NaN,577
577,ATOM,578,,CD,,ARG,,A,70,,...,24.683,16.203,55.874,1.0,0.0,,,C,NaN,578
578,ATOM,579,,NE,,ARG,,A,70,,...,23.785,16.747,56.874,1.0,0.0,,,N,NaN,579
579,ATOM,580,,CZ,,ARG,,A,70,,...,24.152,17.640,57.787,1.0,0.0,,,C,NaN,580
580,ATOM,581,,NH1,,ARG,,A,70,,...,25.407,18.096,57.825,1.0,0.0,,,N,NaN,581
581,ATOM,582,,NH2,,ARG,,A,70,,...,23.263,18.061,58.675,1.0,0.0,,,N,NaN,582
582,ATOM,583,,N,,PRO,,A,71,,...,26.089,13.739,51.069,1.0,0.0,,,N,NaN,583
583,ATOM,584,,CA,,PRO,,A,71,,...,27.273,13.414,50.267,1.0,0.0,,,C,NaN,584
584,ATOM,585,,C,,PRO,,A,71,,...,28.508,14.089,50.850,1.0,0.0,,,C,NaN,585
585,ATOM,586,,O,,PRO,,A,71,,...,28.427,14.719,51.888,1.0,0.0,,,O,NaN,586
586,ATOM,587,,CB,,PRO,,A,71,,...,26.913,13.980,48.896,1.0,0.0,,,C,NaN,587
587,ATOM,588,,CG,,PRO,,A,71,,...,26.045,15.150,49.245,1.0,0.0,,,C,NaN,588
588,ATOM,589,,CD,,PRO,,A,71,,...,25.146,14.561,50.290,1.0,0.0,,,C,NaN,589

In [70]:
pl1.df['ATOM'].head()

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
0,ATOM,1,,N,,MET,,A,1,,...,38.763,40.932,11.492,1.0,0.0,,,N,NaN,1
1,ATOM,2,,CA,,MET,,A,1,,...,37.390,40.466,11.665,1.0,0.0,,,C,NaN,2
2,ATOM,3,,C,,MET,,A,1,,...,36.434,41.158,10.694,1.0,0.0,,,C,NaN,3
3,ATOM,4,,O,,MET,,A,1,,...,36.174,40.649,9.601,1.0,0.0,,,O,NaN,4
4,ATOM,5,,CB,,MET,,A,1,,...,36.924,40.679,13.110,1.0,0.0,,,C,NaN,5

In [71]:
pl1.df['ATOM'].columns

Index(['record_name', 'atom_number', 'blank_1', 'atom_name', 'alt_loc',
       'residue_name', 'blank_2', 'chain_id', 'residue_number', 'insertion',
       'blank_3', 'x_coord', 'y_coord', 'z_coord', 'occupancy', 'b_factor',
       'blank_4', 'segment_id', 'element_symbol', 'charge', 'line_idx'],
      dtype='object')

In [72]:
pl1.df['ATOM']=pl1.df['ATOM'][pl1.df['ATOM'].atom_name == 'CA']

In [73]:
pl1.df['ATOM'].head()

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
1,ATOM,2,,CA,,MET,,A,1,,...,37.390,40.466,11.665,1.0,0.0,,,C,NaN,2
9,ATOM,10,,CA,,SER,,A,2,,...,34.813,42.979,10.397,1.0,0.0,,,C,NaN,10
15,ATOM,16,,CA,,CYS,,A,3,,...,34.220,43.589,6.704,1.0,0.0,,,C,NaN,16
21,ATOM,22,,CA,,LEU,,A,4,,...,31.657,45.701,4.835,1.0,0.0,,,C,NaN,22
29,ATOM,30,,CA,,VAL,,A,5,,...,30.549,44.996,1.261,1.0,0.0,,,C,NaN,30

In [74]:
pl1.df['ATOM'].columns

Index(['record_name', 'atom_number', 'blank_1', 'atom_name', 'alt_loc',
       'residue_name', 'blank_2', 'chain_id', 'residue_number', 'insertion',
       'blank_3', 'x_coord', 'y_coord', 'z_coord', 'occupancy', 'b_factor',
       'blank_4', 'segment_id', 'element_symbol', 'charge', 'line_idx'],
      dtype='object')

In [75]:
pl1.df['ATOM'].drop(['blank_1','alt_loc', 'blank_2','insertion',
       'blank_3', 'blank_4', 'segment_id', 'element_symbol', 'charge', 'line_idx'], axis= 1)
pl1.to_pdb(path='erased.pdb', 
            records=None, 
            gz=False, 
            append_newline=True)

/home/bahram/anaconda3/envs/fastai/lib/python3.6/site-packages/biopandas/pdb/pandas_pdb.py:519: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  df = pd.concat(dfs)

In [42]:
pl1.to_pdb(path='erased.pdb', 
            records=None, 
            gz=False, 
            append_newline=True)

/home/bahram/anaconda3/envs/fastai/lib/python3.6/site-packages/biopandas/pdb/pandas_pdb.py:519: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  df = pd.concat(dfs)

In [76]:
pl2 = PandasPdb().read_pdb('erased.pdb')

In [77]:
pl2.df['ATOM'].shape

(7865, 21)